name: school_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  mailer: ^6.1.0
  restart_app: ^1.3.2
  image_picker: ^1.1.1
  cached_network_image: ^3.4.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  percent_indicator: ^4.2.2
  url_launcher: ^6.3.0
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # ✅ For icon & splash setup
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/edlive_img.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/edlive_img.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/edlive_img.png
  android: true
  ios: true

  # 👇 Make full image fit — no zoom or crop
  android_gravity: center
  ios_content_mode: scaleAspectFit

  # 👇 Optional but helpful if you want image to keep ratio nicely
  fullscreen: true


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
